// angular-ui/src/app/new-image/new-image.component.ts
import { Component, OnInit } from '@angular/core';

import { ImageItem } from '../image-item';
import { ImageService } from '../image.service';

@Component({
  selector: 'app-new-image',
  templateUrl: './new-image.component.html',
  styleUrls: ['./new-image.component.css']
})
export class NewImageComponent implements OnInit {

  data: ImageItem;

  constructor(
    private imageService: ImageService
  ) { 
    this.data = new ImageItem();
  }

  ngOnInit() {
  }

  dataMissing() {
    return !this.data.url || !this.data.name;
  }
  
  addNewImage() {
    this.imageService.addImage(this.data);
  }
}

<div class="image">
  <div class="add-image">
    <div class="row">
      <h4>New image</h4>
    </div>
    <div class="row">
      <input 
        type="text" 
        placeholder="name"
        [(ngModel)]="data.name"
      />
    </div>
    
    <div class="row">
      <input 
        type="text" 
        placeholder="url"
        [(ngModel)]="data.url"/>
    </div>
    <div class="row">
      <button 
        [disabled]="dataMissing()"
        (click)="addNewImage()">
        Add
      </button>
    </div>            
  </div>
</div>

// vue/src/components/NewImage.vue
<template>
  <div class="image">
    <div class="add-image">
      <div class="row">
        <h4>New image</h4>
      </div>
      <div class="row">
        <input 
          type="text" 
          placeholder="name"
          v-model="fields.name"
        />
      </div>
      
      <div class="row">
        <input 
          type="text" 
          placeholder="url"
          v-model="fields.url"
        />
      </div>
      <div class="row">
        <button
          v-on:click="addImage()"
          v-bind:disabled="dataMissing">
          Add
        </button>
      </div>            
    </div>
  </div>
</template>

<script>
  import ImageService from '@/service/image.service';
  const imageService = ImageService.instance();

  export default {
    data() {
      return {
        fields: {
          name: '',
          url: ''
        },
        dataMissing: true
      }
    },

    watch: {
      'fields.name': function(newValue) {
        this.validateData();
      },
      'fields.url': function(newValue) {
        this.validateData();
      }
    },

    methods: {
      addImage() {
        imageService.addImage(this.fields);
      },

      validateData() {
        this.dataMissing = !this.fields.name || !this.fields.url;
      },      
    },   
  }
</script>
