// vue-ui/src/components/Image.vue
<template>
  <div class="image" v-on:click="openDetails()">
    <img v-bind:src="imgData.url"/>
    <div class="remove" v-on:click.stop="removeImage()">x</div>
    <div class="name">{{imgData.name}}</div>
  </div>
</template>

<script>
  import router from '../router';
  import ImageService from '@/service/image.service';
  const imageService = ImageService.instance();

  export default {
    props: ['imgData'],

    methods: {
      openDetails() {
        router.push(`/images/${this.imgData.id}`);
      },
      removeImage() {
        imageService.removeImage(this.imgData.id);
      }
    }
  }
</script>

// react-ui/src/components/Image.js
import React, { Component } from 'react';

class Image extends Component {

  openDetails() {
  }

  removeImage() {
  }

  handleClick() {
    this.props.clicked(this.props.imgData.id);
  }

  render() {
    return (
      <div className="image" onClick={this.handleClick.bind(this)}>
        <img src={this.props.imgData.url} alt='' />
        <div className="remove" />
        <div className="name">{this.props.imgData.name}</div>
      </div>
    );
  }
}

export default Image;
