// vue-ui/src/components/ImageGrid.vue
<template>
  <div class="images">
    <image-item 
      v-bind:img-data="image" 
      v-bind:key="image.id" 
      v-for="image in images">
    </image-item>
    <new-image></new-image>
  </div>
</template>

<script>
  import Vue from 'vue';
  import ImageService from '../service/image.service';
  import Image from './Image.vue';
  import NewImage from './NewImage.vue';
  const imageService = ImageService.instance();

  export default {
    data() {
      return {
        images: imageService.store.images
      }
    },

    created() {
      imageService.loadImages();
    },

    components: {
      'image-item': Image,
      'new-image': NewImage
    },
  };
</script>

// react-ui/src/components/ImageGrid.js
import React, { Component } from 'react';
import { Redirect } from 'react-router-dom';

import Image from './Image';
import NewImage from './NewImage';
import ImageService from '../service/image.service';

const imageService = ImageService.instance();

class ImageGrid extends Component {
  
  constructor() {
    super();
    this.state = {
      images: [],
      redirectTo: null
    };
  }

  componentDidMount() {
    imageService.loadImages().then((images) => {
      this.setState({
        images: images
      });
    });
  }

  imageClicked(imgId) {
    console.log('clicked ', imgId);
    this.setState({
      redirectTo: `/images/${imgId}`
    });
  }

  render() {
    if (this.state.redirectTo) {
      return <Redirect to={this.state.redirectTo} />
    }

    const imageElements = this.state.images.map((image) => {
      return (
        <Image 
          key={image.id} 
          imgData={image}
          clicked={this.imageClicked.bind(this)}
        />
      );
    });

    return (
      <div className="images">
        {imageElements}
        <NewImage />
      </div>
    );
  }
}

export default ImageGrid;
