// vue/src/components/NewImage.vue
<template>
  <div class="image">
    <div class="add-image">
      <div class="row">
        <h4>New image</h4>
      </div>
      <div class="row">
        <input 
          type="text" 
          placeholder="name"
          v-model="fields.name"
        />
      </div>
      
      <div class="row">
        <input 
          type="text" 
          placeholder="url"
          v-model="fields.url"
        />
      </div>
      <div class="row">
        <button
          v-on:click="addImage()"
          v-bind:disabled="dataMissing">
          Add
        </button>
      </div>            
    </div>
  </div>
</template>

<script>
  import ImageService from '@/service/image.service';
  const imageService = ImageService.instance();

  export default {
    data() {
      return {
        fields: {
          name: '',
          url: ''
        },
        dataMissing: true
      }
    },

    watch: {
      'fields.name': function(newValue) {
        this.validateData();
      },
      'fields.url': function(newValue) {
        this.validateData();
      }
    },

    methods: {
      addImage() {
        imageService.addImage(this.fields);
      },

      validateData() {
        this.dataMissing = !this.fields.name || !this.fields.url;
      },      
    },   
  }
</script>

// react-ui/src/components/NewImage.js
import React, { Component } from 'react';

class NewImage extends Component {

  constructor() {
    super();
    this.state = {
      name: '',
      url: '',
      dataMissing: true
    };
  }

  nameChange(event) {
    const dataMissing = this.validateData();
    this.setState({
      name: event.target.value,
      dataMissing: dataMissing
    });

  }

  urlChange(event) {
    const dataMissing = this.validateData();
    this.setState({
      url: event.target.value,
      dataMissing: dataMissing
    });
  }

  validateData() {
    return !this.state.name.length || !this.state.url.length;
  }

  saveImage() {
    this.props.addImage({
      name: this.state.name,
      url: this.state.url
    });
  }

  render() {
    return (
      <div className='image'>
        <div className='add-image'>
          <div className='row'>
            <h4>New image</h4>
          </div>
          <div className='row'>
            <input
              type='text'
              placeholder='name'
              value={this.state.name}
              onInput={this.nameChange.bind(this)}
            />
          </div>
          <div className='row'>
            <input
              type='text'
              placeholder='url'
              value={this.state.url}
              onInput={this.urlChange.bind(this)}
            />
          </div>
          <div className='row'>
            <button
              onClick={this.saveImage.bind(this)}
              disabled={this.state.dataMissing}>
              Add
            </button>
          </div>
        </div>
      </div>
    );
  }
}

export default NewImage;
